# Countries data
from typing import List

from pydantic import BaseModel, Field


class Country(BaseModel):
    name: str = Field(..., description="The name of the country")
    country_code: str = Field(..., description="The phone code of the country")


class CountriesList(BaseModel):
    countries: List[Country] = Field(
        ..., description="List of countries and their phone codes"
    )


countries_data = CountriesList(
    countries=[
        {"name": "Afghanistan", "country_code": "+93"},
        {"name": "Albania", "country_code": "+355"},
        {"name": "Algeria", "country_code": "+213"},
        {"name": "Andorra", "country_code": "+376"},
        {"name": "Angola", "country_code": "+244"},
        {"name": "Argentina", "country_code": "+54"},
        {"name": "Armenia", "country_code": "+374"},
        {"name": "Australia", "country_code": "+61"},
        {"name": "Austria", "country_code": "+43"},
        {"name": "Azerbaijan", "country_code": "+994"},
        {"name": "Bahamas", "country_code": "+1-242"},
        {"name": "Bahrain", "country_code": "+973"},
        {"name": "Bangladesh", "country_code": "+880"},
        {"name": "Barbados", "country_code": "+1-246"},
        {"name": "Belarus", "country_code": "+375"},
        {"name": "Belgium", "country_code": "+32"},
        {"name": "Belize", "country_code": "+501"},
        {"name": "Benin", "country_code": "+229"},
        {"name": "Bhutan", "country_code": "+975"},
        {"name": "Bolivia", "country_code": "+591"},
        {"name": "Bosnia and Herzegovina", "country_code": "+387"},
        {"name": "Botswana", "country_code": "+267"},
        {"name": "Brazil", "country_code": "+55"},
        {"name": "Brunei", "country_code": "+673"},
        {"name": "Bulgaria", "country_code": "+359"},
        {"name": "Burkina Faso", "country_code": "+226"},
        {"name": "Burundi", "country_code": "+257"},
        {"name": "Cambodia", "country_code": "+855"},
        {"name": "Cameroon", "country_code": "+237"},
        {"name": "Canada", "country_code": "+1"},
        {"name": "Cape Verde", "country_code": "+238"},
        {"name": "Central African Republic", "country_code": "+236"},
        {"name": "Chad", "country_code": "+235"},
        {"name": "Chile", "country_code": "+56"},
        {"name": "China", "country_code": "+86"},
        {"name": "Colombia", "country_code": "+57"},
        {"name": "Comoros", "country_code": "+269"},
        {"name": "Congo", "country_code": "+242"},
        {"name": "Costa Rica", "country_code": "+506"},
        {"name": "Croatia", "country_code": "+385"},
        {"name": "Cuba", "country_code": "+53"},
        {"name": "Cyprus", "country_code": "+357"},
        {"name": "Czech Republic", "country_code": "+420"},
        {"name": "Denmark", "country_code": "+45"},
        {"name": "Djibouti", "country_code": "+253"},
        {"name": "Dominica", "country_code": "+1-767"},
        {"name": "Dominican Republic", "country_code": "+1-809"},
        {"name": "Ecuador", "country_code": "+593"},
        {"name": "Egypt", "country_code": "+20"},
        {"name": "El Salvador", "country_code": "+503"},
        {"name": "Equatorial Guinea", "country_code": "+240"},
        {"name": "Eritrea", "country_code": "+291"},
        {"name": "Estonia", "country_code": "+372"},
        {"name": "Eswatini", "country_code": "+268"},
        {"name": "Ethiopia", "country_code": "+251"},
        {"name": "Fiji", "country_code": "+679"},
        {"name": "Finland", "country_code": "+358"},
        {"name": "France", "country_code": "+33"},
        {"name": "Gabon", "country_code": "+241"},
        {"name": "Gambia", "country_code": "+220"},
        {"name": "Georgia", "country_code": "+995"},
        {"name": "Germany", "country_code": "+49"},
        {"name": "Ghana", "country_code": "+233"},
        {"name": "Greece", "country_code": "+30"},
        {"name": "Grenada", "country_code": "+1-473"},
        {"name": "Guatemala", "country_code": "+502"},
        {"name": "Guinea", "country_code": "+224"},
        {"name": "Guyana", "country_code": "+592"},
        {"name": "Haiti", "country_code": "+509"},
        {"name": "Honduras", "country_code": "+504"},
        {"name": "Hungary", "country_code": "+36"},
        {"name": "Iceland", "country_code": "+354"},
        {"name": "India", "country_code": "+91"},
        {"name": "Indonesia", "country_code": "+62"},
        {"name": "Iran", "country_code": "+98"},
        {"name": "Iraq", "country_code": "+964"},
        {"name": "Ireland", "country_code": "+353"},
        {"name": "Israel", "country_code": "+972"},
        {"name": "Italy", "country_code": "+39"},
        {"name": "Jamaica", "country_code": "+1-876"},
        {"name": "Japan", "country_code": "+81"},
        {"name": "Jordan", "country_code": "+962"},
        {"name": "Kazakhstan", "country_code": "+7"},
        {"name": "Kenya", "country_code": "+254"},
        {"name": "Kiribati", "country_code": "+686"},
        {"name": "Kuwait", "country_code": "+965"},
        {"name": "Kyrgyzstan", "country_code": "+996"},
        {"name": "Laos", "country_code": "+856"},
        {"name": "Latvia", "country_code": "+371"},
        {"name": "Lebanon", "country_code": "+961"},
        {"name": "Lesotho", "country_code": "+266"},
        {"name": "Liberia", "country_code": "+231"},
        {"name": "Libya", "country_code": "+218"},
        {"name": "Liechtenstein", "country_code": "+423"},
        {"name": "Lithuania", "country_code": "+370"},
        {"name": "Luxembourg", "country_code": "+352"},
        {"name": "Madagascar", "country_code": "+261"},
        {"name": "Malawi", "country_code": "+265"},
        {"name": "Malaysia", "country_code": "+60"},
        {"name": "Maldives", "country_code": "+960"},
        {"name": "Mali", "country_code": "+223"},
        {"name": "Malta", "country_code": "+356"},
        {"name": "Mauritania", "country_code": "+222"},
        {"name": "Mauritius", "country_code": "+230"},
        {"name": "Mexico", "country_code": "+52"},
        {"name": "Moldova", "country_code": "+373"},
        {"name": "Monaco", "country_code": "+377"},
        {"name": "Mongolia", "country_code": "+976"},
        {"name": "Montenegro", "country_code": "+382"},
        {"name": "Morocco", "country_code": "+212"},
        {"name": "Mozambique", "country_code": "+258"},
        {"name": "Myanmar", "country_code": "+95"},
        {"name": "Namibia", "country_code": "+264"},
        {"name": "Nauru", "country_code": "+674"},
        {"name": "Nepal", "country_code": "+977"},
        {"name": "Netherlands", "country_code": "+31"},
        {"name": "New Zealand", "country_code": "+64"},
        {"name": "Nicaragua", "country_code": "+505"},
        {"name": "Niger", "country_code": "+227"},
        {"name": "Nigeria", "country_code": "+234"},
        {"name": "Norway", "country_code": "+47"},
        {"name": "Oman", "country_code": "+968"},
        {"name": "Pakistan", "country_code": "+92"},
        {"name": "Palau", "country_code": "+680"},
        {"name": "Panama", "country_code": "+507"},
        {"name": "Papua New Guinea", "country_code": "+675"},
        {"name": "Paraguay", "country_code": "+595"},
        {"name": "Peru", "country_code": "+51"},
        {"name": "Philippines", "country_code": "+63"},
        {"name": "Poland", "country_code": "+48"},
        {"name": "Portugal", "country_code": "+351"},
        {"name": "Qatar", "country_code": "+974"},
        {"name": "Romania", "country_code": "+40"},
        {"name": "Russia", "country_code": "+7"},
        {"name": "Rwanda", "country_code": "+250"},
        {"name": "Saint Kitts and Nevis", "country_code": "+1-869"},
        {"name": "Saint Lucia", "country_code": "+1-758"},
        {"name": "Saint Vincent and the Grenadines", "country_code": "+1-784"},
        {"name": "Samoa", "country_code": "+685"},
        {"name": "San Marino", "country_code": "+378"},
        {"name": "Sao Tome and Principe", "country_code": "+239"},
        {"name": "Saudi Arabia", "country_code": "+966"},
        {"name": "Senegal", "country_code": "+221"},
        {"name": "Serbia", "country_code": "+381"},
        {"name": "Seychelles", "country_code": "+248"},
        {"name": "Sierra Leone", "country_code": "+232"},
        {"name": "Singapore", "country_code": "+65"},
        {"name": "Slovakia", "country_code": "+421"},
        {"name": "Slovenia", "country_code": "+386"},
        {"name": "Solomon Islands", "country_code": "+677"},
        {"name": "Somalia", "country_code": "+252"},
        {"name": "South Africa", "country_code": "+27"},
        {"name": "South Korea", "country_code": "+82"},
        {"name": "Spain", "country_code": "+34"},
        {"name": "Sri Lanka", "country_code": "+94"},
        {"name": "Sudan", "country_code": "+249"},
        {"name": "Suriname", "country_code": "+597"},
        {"name": "Sweden", "country_code": "+46"},
        {"name": "Switzerland", "country_code": "+41"},
        {"name": "Syria", "country_code": "+963"},
        {"name": "Taiwan", "country_code": "+886"},
        {"name": "Tajikistan", "country_code": "+992"},
        {"name": "Tanzania", "country_code": "+255"},
        {"name": "Thailand", "country_code": "+66"},
        {"name": "Togo", "country_code": "+228"},
        {"name": "Tonga", "country_code": "+676"},
        {"name": "Trinidad and Tobago", "country_code": "+1-868"},
        {"name": "Tunisia", "country_code": "+216"},
        {"name": "Turkey", "country_code": "+90"},
        {"name": "Turkmenistan", "country_code": "+993"},
        {"name": "Tuvalu", "country_code": "+688"},
        {"name": "Uganda", "country_code": "+256"},
        {"name": "Ukraine", "country_code": "+380"},
        {"name": "United Arab Emirates", "country_code": "+971"},
        {"name": "United Kingdom", "country_code": "+44"},
        {"name": "United States", "country_code": "+1"},
        {"name": "Uruguay", "country_code": "+598"},
        {"name": "Uzbekistan", "country_code": "+998"},
        {"name": "Vanuatu", "country_code": "+678"},
        {"name": "Venezuela", "country_code": "+58"},
        {"name": "Vietnam", "country_code": "+84"},
        {"name": "Yemen", "country_code": "+967"},
        {"name": "Zambia", "country_code": "+260"},
        {"name": "Zimbabwe", "country_code": "+263"},
    ]
)
